name: Using Logs Groups

on:
  push:

jobs:
  log_group:
    runs-on: ubuntu-latest
    steps:
      - name: Création Groupe Log Ecole-IT
        run: |
          echo "::group::ecole-it"
          echo "hello, ecole-it"
          echo "::endgroup::"
          echo "ceci n'est pas dans le groupe"
